export const companyData = [
    {
      "Manufacturer": "JCR Pharma",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.jcrpharm.co.jp/en/site/en/company/office.html",
      "Company LinkedIn": "N/A",
      "Manufacturer Locations": "Japan",
      "Manufacturer Type": "R&D",
      "Founded": 1975,
      "Number of Employees": "501-1000",
      "Specialties2": "Cell therapy, Regenerative medicine, Vaccine development",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "Bio-Manguinhos Fiocruz",
      "Company Stage": "State-owned enterprise",
      "Company Website": "https://www.ini.fiocruz.br/",
      "Company LinkedIn": "N/A",
      "Manufacturer Locations": "Brazil",
      "Manufacturer Type": "R&D",
      "Founded": 1918,
      "Number of Employees": "1001-5000",
      "Specialties2": "Vaccines, Vaccine Manufacturing, Pharmacokinetics, Regulatory Affairs, Conducting Clinical Studies, Data Processing, Organization of Biorepositories, Sample Processing and Analysis, Database of Clinical Records",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Phased full process"
    },
    {
      "Manufacturer": "Shenzhen Kangtai Biological Products Ltd.",
      "Company Stage": "Publicly traded",
      "Company Website": "https://en.biokangtai.com/C3.html",
      "Company LinkedIn": "https://www.linkedin.com/company/biokangtai/",
      "Manufacturer Locations": "China",
      "Manufacturer Type": "cGMP",
      "Founded": 1992,
      "Number of Employees": "1001-5000",
      "Specialties2": "COVID-19 inactivated vaccine production based on adenovirus vector, cGMP",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Serum Institute of India Pvt. Ltd.",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.seruminstitute.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/serum-institute-of-india-limited/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "cGMP",
      "Founded": 1966,
      "Number of Employees": "1001-5000",
      "Specialties2": "Human Vaccines, Bacterial Vaccines, Viral Vaccines, Recombinant and Combination Vaccines, Polysaccharide Conjugate Vaccines, Influenza Vaccines, Antisera, and Recombinant Products",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Siam Bioscience",
      "Company Stage": "Privately held",
      "Company Website": "https://www.siambioscience.com/?lang=en",
      "Company LinkedIn": "https://www.linkedin.com/in/pimonratketsawatsomkron/",
      "Manufacturer Locations": "Thailand",
      "Manufacturer Type": "R&D, Manufacturing",
      "Founded": 2009,
      "Number of Employees": "201-500",
      "Specialties2": "Covid-19 Vaccine, Mammalian cell culture derived biopharmaceuticals, Cancer, Autoimmune Diseases, Biocosmeceuticals and Anemia",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "IRBM",
      "Company Stage": "Privately held",
      "Company Website": "https://www.irbm.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/irbm-science-park-s-p-a-/",
      "Manufacturer Locations": "Italy",
      "Manufacturer Type": "R&D, Manufacturing",
      "Founded": 2000,
      "Number of Employees": "201-500",
      "Specialties2": "Drug Discovery, DMPK, Peptide Chemistry, Medicinal Chemistry, Assay Development, High-Throughput Screening, Preclinical Research, Pharmacology, Biochemistry, NMR, Infectious Diseases, Neurodegeneration, and Oncology",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "mAbxience",
      "Company Stage": "Privately held",
      "Company Website": "https://www.linkedin.com/company/mabxience/",
      "Company LinkedIn": "https://www.mabxience.com/",
      "Manufacturer Locations": "Spain",
      "Manufacturer Type": "CDMO",
      "Founded": 2009,
      "Number of Employees": "501-1000",
      "Specialties2": "cGMP Manufacturing, Fed Batch, Perfusion, Cell line development, Monoclonal Antibodies, Cytokines, Chimeric Proteins, Recombinant Hormones, Adenoviral Vaccines, Bacilovirus Vaccines, Glycosylated Recombinant Proteins",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "HALIX B.V.",
      "Company Stage": "Privately held",
      "Company Website": "https://www.halix.nl/",
      "Company LinkedIn": "https://www.linkedin.com/company/halix/",
      "Manufacturer Locations": "Netherlands",
      "Manufacturer Type": "CDMO",
      "Founded": 2012,
      "Number of Employees": "N/a",
      "Specialties2": "Development & Manufacturing of Biologics, Viral Vector Manufacturing, Recombinant Protein Products, Drug Substances & Drug Products, GMP Manufacturing, and Biotechnology",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Oxford Biomedica",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.oxb.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/oxford-biomedica/",
      "Manufacturer Locations": "United Kingdom",
      "Manufacturer Type": "CDMO",
      "Founded": 1995,
      "Number of Employees": "501-1000",
      "Specialties2": "Gene Therapy, Immunotherapy, Viral Vector GMP Manufacturing",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Curia (formerly AMRI)",
      "Company Stage": "Publicly traded",
      "Company Website": "https://curiaglobal.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/curia-cdmo/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "CDMO",
      "Founded": 1991,
      "Number of Employees": "1001-5000",
      "Specialties2": "Contract Research, Discovery Biology, Early Development, Pre-Formulation, Contract Manufacturing, Formulation, Aseptic Fill Finish, Syringe and Vial Filling, Clinical/Commercial APIs, Lyophilization, Controlled Substances, Stability Testing, High Potency, Generics",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "Catalent Pharma Solutions",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.catalent.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/catalent-pharma-solutions/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "R&D, Manufacturing, Regulatory",
      "Founded": 2007,
      "Number of Employees": "10000+",
      "Specialties2": "Analytical Chemistry, Clinical Supply, Biotech, Pharmaceutical Supply Chain, Biologics, Respiratory, Formulation Development, Drug Delivery, Clinical Packaging, Drug Delivery, Dose Form Manufacturing, Gene Therapy, Vaccine Production, Pharmaceutical, Drug Development, Cell Therapy",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Emergent BioSolutions",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.emergentbiosolutions.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/emergent-biosolutions/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "CDMO",
      "Founded": 1998,
      "Number of Employees": "1001-5000",
      "Specialties2": "Manufacturing, Partnering, M&A, Devices Development, Vaccine Development, Therapeutics Development, and Contract Development and Manufacturing",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Cobra Biologics, A Charles River Company",
      "Company Stage": "Privately held",
      "Company Website": "http://www.cobrabio.com",
      "Company LinkedIn": "https://www.linkedin.com/company/cobrabiologics/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "CDMO",
      "Founded": 1992,
      "Number of Employees": "201-500",
      "Specialties2": "Plasmid DNA, Gene Therapies, Immunotherapies, Viral Vectors, Cell Therapy, Plasmid Vectors, Viral  Vector Packaging, cGMP Manufacturing, API Fill & Finish, Aseptic Pharmaceutical Manufacturing",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Novasep SAS",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.novasep.com",
      "Company LinkedIn": "https://www.linkedin.com/company/novasep/",
      "Manufacturer Locations": "France",
      "Manufacturer Type": "CDMO",
      "Founded": 1993,
      "Number of Employees": "1001-5000",
      "Specialties2": "Custom Synthesis, API Manufacturing, Membrane Filtration, Preparative Chromatography, Biomanufacturing, Biopharmaceuticals Manufacturing, Downstream Processing, Upstream Processing, Purification Processes, Chromatography",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "IDT Biologika",
      "Company Stage": "Privately held",
      "Company Website": "https://idt-biologika.com",
      "Company LinkedIn": "https://www.linkedin.com/company/idtbiologika/",
      "Manufacturer Locations": "Germany",
      "Manufacturer Type": "CDMO",
      "Founded": 1921,
      "Number of Employees": "1001-5000",
      "Specialties2": "Cell Lines, Viral Vaccines, Viral Vectors for Gene and Immune Therapeutics, Oncolytic Viruses, Virus-Like Particles, Aseptic Fill and Finish, End-to-end Capabilities",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Phased full process"
    },
    {
      "Manufacturer": "CSL",
      "Company Stage": "Publicly traded",
      "Company Website": "http://www.csl.com",
      "Company LinkedIn": "https://www.linkedin.com/company/csl/",
      "Manufacturer Locations": "Australia",
      "Manufacturer Type": "R&D",
      "Founded": 1916,
      "Number of Employees": "10000+",
      "Specialties2": "Complex Biologicals, Vaccines, Plasma, Plasma Derived Therapeutics, Biotechnology",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Wockhardt Ltd.",
      "Company Stage": "Publicly traded",
      "Company Website": "http://www.wockhardt.com",
      "Company LinkedIn": "https://www.linkedin.com/company/wockhardt/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "Contract Manufacturing",
      "Founded": 1999,
      "Number of Employees": "5001-10000",
      "Specialties2": "Formulations, Biopharmaceuticals, Active Pharmaceutical Ingredients, Vaccines, cGMP Manufacturing, Biosimilars, Novel Drug Delivery Systems, Generics, Fill and Finish",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "R-Pharm",
      "Company Stage": "Privately held",
      "Company Website": "http://www.r-pharm.com",
      "Company LinkedIn": "https://www.linkedin.com/company/r-pharm/",
      "Manufacturer Locations": "Russian Federation",
      "Manufacturer Type": "Contract Manufacturing",
      "Founded": 2001,
      "Number of Employees": "1001-5000",
      "Specialties2": "cGMP Manufacturing, Vaccines, Pharnaceutical Manufacturing, Pharmaceutical Distribution, R&D, Promotion, R&D",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Insud Pharma",
      "Company Stage": "Privately held",
      "Company Website": "https://www.insudpharma.com/en/",
      "Company LinkedIn": "https://www.linkedin.com/company/insud-pharma/",
      "Manufacturer Locations": "Spain",
      "Manufacturer Type": "CDMO",
      "Founded": 1977,
      "Number of Employees": "5001-10000",
      "Specialties2": "Active pharmaceutical ingredients (APIs), Finished dosage forms (FDFs), Women`s Health, Respiratory Health, Cardiovascular, Animal Health, Biopharmaceuticals, Branded pharmaceuticals, Gastroenterology, Dermatology, Major therapeutic areas, and Central nervous system",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "Wuxi Biologics",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.wuxibiologics.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/wuxibiologics/",
      "Manufacturer Locations": "Hong Kong",
      "Manufacturer Type": "R&D, Contract Manufacturing",
      "Founded": 2010,
      "Number of Employees": "10000+",
      "Specialties2": "Biologics Conjugation, Bioprocess CMC, Biosafety, Biologics GMP Manufacturing, Biologics Discovery Service, Cell Line Development, Formulation Development, Analytical Characterization, Cell Culture and Purification Process Development, Monoclonal Antibodies (mAbs), Vaccine Development, Vaccine Manufacturing, Antibody Discovery, Antibody Manufacturing, Protein Production, Analytical Services, Biotherapeutics, Biopharmaceuticals, Continuous Manufacturing",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "Nipro Corporation",
      "Company Stage": "Publicly traded",
      "Company Website": "https://nipro.com/info/",
      "Company LinkedIn": "https://www.linkedin.com/company/nipro-medical-corporation/",
      "Manufacturer Locations": "Japan",
      "Manufacturer Type": "Contract Manufacturing",
      "Founded": 1954,
      "Number of Employees": "10000+",
      "Specialties2": "Vaccines, Custom Medical Manufacturing Solutions, Medical-Surgical Medical Devices, Renal Medical Devices, Vascular Access Medical Devices, Vascular, Renal, Veterinary Products, Hemodialysis, Hospital products, OEM, Technical Services, ducation",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "Ajinomoto Bio-Pharma Services",
      "Company Stage": "Publicly traded",
      "Company Website": "http://www.ajibio-pharma.com",
      "Company LinkedIn": "https://www.linkedin.com/company/ajibio-pharma-services/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "CDMO",
      "Founded": 1909,
      "Number of Employees": "1001-5000",
      "Specialties2": "Corynex® Protein Expression Technology, Oligonucleotide Synthesis, Antibody Drug Conjugations (ADC), High Potency APIs (HPAPI), Biocatalysis, Continuous Flow Manufacturing, Vaccines",
      "Track Record": "AstraZeneca/Oxford",
      "Arrangement Category": "Bulk substance and Fill-and-finish"
    },
    {
      "Manufacturer": "Haffkine Biopharmaceutical Corporation Ltd",
      "Company Stage": "State-owned enterprise",
      "Company Website": "https://www.vaccinehaffkine.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/haffkine-biopharmaceutical-co.-limited/about/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "Contract Manufacturing",
      "Founded": 1956,
      "Number of Employees": "51-200",
      "Specialties2": "cGMP Manufacturing, Vaccine Manufacturing. Qualitative Manufacturing",
      "Track Record": "Bharat Biotech",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Bharat Immunologicals and Biologicals Limited",
      "Company Stage": "State-owned enterprise",
      "Company Website": "http://www.bibcol.com",
      "Company LinkedIn": "https://www.linkedin.com/company/bharat-immunologicals-and-biologicals-corporation-ltd/about/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "N/A",
      "Founded": 1989,
      "Number of Employees": "51-200",
      "Specialties2": "N/A",
      "Track Record": "Bharat Biotech",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Indian Immunologicals Limited",
      "Company Stage": "State-owned enterprise",
      "Company Website": "https://www.indimmune.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/indian-immunologicals-limited/?originalSubdomain=in",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "N/A",
      "Founded": 1982,
      "Number of Employees": "1001-5000",
      "Specialties2": "N/A",
      "Track Record": "Bharat Biotech",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Ocugen Inc",
      "Company Stage": "Publicly traded",
      "Company Website": "https://ocugen.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/ocugen/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "N/A",
      "Founded": 2013,
      "Number of Employees": "51-200",
      "Specialties2": "N/A",
      "Track Record": "Bharat Biotech",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Jubilant HollisterStier",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.jublhs.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/jhs-cmo/",
      "Manufacturer Locations": "United States",
      "Manufacturer Type": "N/A",
      "Founded": 1921,
      "Number of Employees": "501-1000",
      "Specialties2": "N/A",
      "Track Record": "Bharat Biotech",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Hester Biosciences",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.hester.in/",
      "Company LinkedIn": "https://www.linkedin.com/company/hester-biosciences-limited/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "N/A",
      "Founded": 1987,
      "Number of Employees": "201-500",
      "Specialties2": "N/A",
      "Track Record": "Bharat Biotech",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "Drugmex",
      "Company Stage": "Privately held",
      "Company Website": "https://drugmex.com.mx/en/home/",
      "Company LinkedIn": "https://www.linkedin.com/company/drugmex/",
      "Manufacturer Locations": "Mexico",
      "Manufacturer Type": "N/A",
      "Founded": 2008,
      "Number of Employees": "51-200",
      "Specialties2": "N/A",
      "Track Record": "CanSino Biologics",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "AJM Pharma Pvt",
      "Company Stage": "Privately held",
      "Company Website": "http://www.ajmpharma.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/ajmpharma/?originalSubdomain=pk",
      "Manufacturer Locations": "Pakistan",
      "Manufacturer Type": "",
      "Founded": 2004,
      "Number of Employees": "201-500",
      "Specialties2": "N/A",
      "Track Record": "CanSino Biologics",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "Petrovax",
      "Company Stage": "Privately held",
      "Company Website": "http://www.petrovax.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/petrovax/",
      "Manufacturer Locations": "Russian Federation",
      "Manufacturer Type": "",
      "Founded": 1996,
      "Number of Employees": "501-1000",
      "Specialties2": "N/A",
      "Track Record": "CanSino Biologics",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Solution Biologics",
      "Company Stage": "Publicly traded",
      "Company Website": "",
      "Company LinkedIn": "",
      "Manufacturer Locations": "Malaysia",
      "Manufacturer Type": "",
      "Founded": "",
      "Number of Employees": "",
      "Specialties2": "N/A",
      "Track Record": "CanSino Biologics",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "Biomm",
      "Company Stage": "Publicly traded",
      "Company Website": "https://biomm.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/biommoficial/",
      "Manufacturer Locations": "Brazil",
      "Manufacturer Type": "",
      "Founded": 2001,
      "Number of Employees": "201-500",
      "Specialties2": "N/A",
      "Track Record": "CanSino Biologics",
      "Arrangement Category": ""
    },
    {
      "Manufacturer": "Espromed Bio",
      "Company Stage": "State-owned enterprise",
      "Company Website": "https://espromedbio.gob.ve/",
      "Company LinkedIn": "",
      "Manufacturer Locations": "Venezuela",
      "Manufacturer Type": "",
      "Founded": "",
      "Number of Employees": "",
      "Specialties2": "N/A",
      "Track Record": "CIGB - Center for Genetic Engineering and Biotechnology",
      "Arrangement Category": ""
    },
    {
      "Manufacturer": "",
      "Company Stage": "Unclear",
      "Company Website": "",
      "Company LinkedIn": "",
      "Manufacturer Locations": "Vietnam",
      "Manufacturer Type": "",
      "Founded": "",
      "Number of Employees": "",
      "Specialties2": "",
      "Track Record": "CIGB - Center for Genetic Engineering and Biotechnology",
      "Arrangement Category": "Phased full process"
    },
    {
      "Manufacturer": "Celonic Group",
      "Company Stage": "Privately held",
      "Company Website": "http://www.celonic.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/celonic-ag/",
      "Manufacturer Locations": "Switzerland, Germany",
      "Manufacturer Type": "",
      "Founded": 1982,
      "Number of Employees": "201-500",
      "Specialties2": "Contract development and Manufacturing (GMP), Cell Line Development, Process and Analytic Development, Biosimilar Antibody Development, Outlicensing of developed Biosimilar Cell Lines, GMP manufacturing at 1000L scale, Fill and Finish, Perfusion, Fed-batch, Biosimilars, NBE, and Cell & Gene Therapy",
      "Track Record": "CureVac",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "Novartis",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.novartis.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/novartis/",
      "Manufacturer Locations": "Switzerland",
      "Manufacturer Type": "",
      "Founded": 1996,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Curevac",
      "Arrangement Category": "Bulk substance production"
    },
    {
      "Manufacturer": "Fareva",
      "Company Stage": "Privately held",
      "Company Website": "https://www.fareva.com/en-gb/",
      "Company LinkedIn": "https://www.linkedin.com/company/fareva/",
      "Manufacturer Locations": "France",
      "Manufacturer Type": "",
      "Founded": 1990,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Curevac",
      "Arrangement Category": "Fill-and-finish"
    },
    {
      "Manufacturer": "Bayer",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.bayer.com/en/",
      "Company LinkedIn": "https://www.linkedin.com/company/bayer/",
      "Manufacturer Locations": "Germany",
      "Manufacturer Type": "",
      "Founded": 1863,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Curevac",
      "Arrangement Category": "Other"
    },
    {
      "Manufacturer": "GlaxoSmithKline",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.gsk.com/en-gb/",
      "Company LinkedIn": "https://www.linkedin.com/company/glaxosmithkline/",
      "Manufacturer Locations": "United Kingdom",
      "Manufacturer Type": "",
      "Founded": 1830,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Curevac",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Rentschler Biopharma SE",
      "Company Stage": "Privately held",
      "Company Website": "https://www.rentschler-biopharma.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/rentschler-biopharma-se/",
      "Manufacturer Locations": "Germany",
      "Manufacturer Type": "",
      "Founded": 1927,
      "Number of Employees": "501-1000",
      "Specialties2": "",
      "Track Record": "Curevac",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "WACKER Chemie AG",
      "Company Stage": "Publicly traded",
      "Company Website": "https://www.wacker.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/wacker/",
      "Manufacturer Locations": "Germany",
      "Manufacturer Type": "",
      "Founded": 1914,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Curevac",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Pasteur Institute",
      "Company Stage": "Government agency",
      "Company Website": "N/a",
      "Company LinkedIn": "https://www.linkedin.com/company/pasteur-institute-of-iran/",
      "Manufacturer Locations": "Iran, Islamic Rep.",
      "Manufacturer Type": "",
      "Founded": 1920,
      "Number of Employees": "201-500",
      "Specialties2": "",
      "Track Record": "Finlay Vaccine Institute",
      "Arrangement Category": ""
    },
    {
      "Manufacturer": "Actoverco",
      "Company Stage": "Unclear",
      "Company Website": "http://www.actoverco.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/actover/",
      "Manufacturer Locations": "Iran, Islamic Rep.",
      "Manufacturer Type": "",
      "Founded": "",
      "Number of Employees": "1001-5000",
      "Specialties2": "",
      "Track Record": "Gamaleya",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Belpharprom",
      "Company Stage": "State-owned enterprise",
      "Company Website": "https://belpharmprom.by/en/",
      "Company LinkedIn": "",
      "Manufacturer Locations": "Belarus",
      "Manufacturer Type": "",
      "Founded": 2017,
      "Number of Employees": "",
      "Specialties2": "",
      "Track Record": "Gamaleya",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "Dr Reddy's",
      "Company Stage": "Publicly traded",
      "Company Website": "http://www.drreddys.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/dr--reddys-laboratories/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "",
      "Founded": 1984,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Gamaleya",
      "Arrangement Category": "Other"
    },
    {
      "Manufacturer": "Hetero",
      "Company Stage": "Privately held",
      "Company Website": "https://heteroworld.com/",
      "Company LinkedIn": "https://www.linkedin.com/company/hetero/",
      "Manufacturer Locations": "India",
      "Manufacturer Type": "",
      "Founded": 1993,
      "Number of Employees": "10000+",
      "Specialties2": "",
      "Track Record": "Gamaleya",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "União Química",
      "Company Stage": "Privately held",
      "Company Website": "",
      "Company LinkedIn": "",
      "Manufacturer Locations": "Brazil",
      "Manufacturer Type": "",
      "Founded": "",
      "Number of Employees": "5001-10000",
      "Specialties2": "",
      "Track Record": "Gamaleya",
      "Arrangement Category": "Full process"
    },
    {
      "Manufacturer": "VisCoran",
      "Company Stage": "Privately held",
      "Company Website": "",
      "Company LinkedIn": "",
      "Manufacturer Locations": "Turkey",
      "Manufacturer Type": "",
      "Founded": "",
      "Number of Employees": "",
      "Specialties2": "",
      "Track Record": "Gamaleya",
      "Arrangement Category": "Full process"
    }
  ]